<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PiViMM" nsURI="http://pivi/1.1" nsPrefix="pivi">
  <eClassifiers xsi:type="ecore:EClass" name="Icons">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeblocks" upperBound="-1"
        eType="#//CodeBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeconnections" upperBound="-1"
        eType="#//Connector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//CodeBlock"/>
  </eClassifiers>
</ecore:EPackage>
